//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechReviewPoint.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.Comments = new HashSet<Comment>();
        }
        [Display(Name = "Review ID")]
        public int ReviewID { get; set; }

        [Display(Name = "Review Point")]
        public Nullable<int> review_point { get; set; }

        [Display(Name = "Review ID")]
        public int UserID { get; set; }
        public int ProductID { get; set; }

        [Display(Name = "Review")]
        public string ReviewPost { get; set; }

        [Display(Name = "Review Date")]
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string Picture { get; set; }

        public HttpPostedFileBase review_img_file { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual Comment Comment { get; set; }

    }
}
